import = ["/home/dropbit/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
#import = ["/home/dropbit/.config/alacritty/rose-pine/rose-pine.toml"]

[font]
size = 15.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "T"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[window]
decorations = "none"
opacity = 0.95 # 0.95
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15
