#import = ["/home/dropbit/.config/alacritty/themes/catppuccin-mocha.toml"]
#import = ["/home/dropbit/.config/alacritty/themes/rose-pine.toml"]
import = ["/home/dropbit/.config/alacritty/themes/gruvbox-dark.toml"]

[cursor]
style.shape = "Beam"
style.blinking = "Off"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 15.0

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "T"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[window]
decorations = "none"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15
